// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onTemperatureChange();
void onSensorChange();
void onRelayChange();

float temperature;
int sensor;
bool relay;

void initProperties(){

  ArduinoCloud.addProperty(temperature, READWRITE, 1 * SECONDS, onTemperatureChange);
  ArduinoCloud.addProperty(sensor, READWRITE, 1 * SECONDS, onSensorChange);
  ArduinoCloud.addProperty(relay, READWRITE, ON_CHANGE, onRelayChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
